-- RETRIEVE ALL COLUMNS AND ROWS FROM THE WALMART TABLE
SELECT * 
FROM walmart;

-- COUNT THE TOTAL NUMBER OF TRANSACTIONS (ROWS) IN THE WALMART TABLE
SELECT COUNT(*) 
FROM walmart;

-- GET A UNIQUE LIST OF CITIES SORTED ALPHABETICALLY
SELECT DISTINCT city AS distict_cities
FROM walmart
ORDER BY 1;

-- COUNT THE NUMBER OF UNIQUE CITIES REPRESENTED IN THE DATASET
SELECT COUNT(DISTINCT city) AS num_of_cities
FROM walmart;

-- GET A UNIQUE LIST OF ALL PAYMENT METHODS USED BY CUSTOMERS
SELECT DISTINCT payment_method 
FROM walmart;

-- COUNT THE NUMBER OF TRANSACTIONS ASSOCIATED WITH EACH PAYMENT METHOD
SELECT payment_method, COUNT(*) 
FROM walmart
GROUP BY payment_method;

-- COUNT THE TOTAL NUMBER OF UNIQUE STORE BRANCHES
SELECT COUNT(DISTINCT branch) 
FROM walmart;

-- FIND THE MINIMUM QUANTITY OF ITEMS PURCHASED IN A SINGLE TRANSACTION
SELECT MIN(quantity)
FROM walmart;

-- FIND THE MAXIMUM QUANTITY OF ITEMS PURCHASED IN A SINGLE TRANSACTION
SELECT MAX(quantity)
FROM walmart;